column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 6
quote_style = "ForceDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"

[sort_requires]
enabled = true
